modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="whydoesntthiswork"
version="1.0.0"
displayName="WHYDOESNTTHISWORK!!!!"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Lee Sudweeks, MCreator"

[[dependencies.whydoesntthiswork]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



